function projectCargoCapacity(){return cargoByCar[S.car.id]||6}
function bodyPanelTransportSlots(k){return ['hood','trunk'].includes(k)?4:['front_bumper','rear_bumper','left_door','right_door'].includes(k)?3:2}

let S=null,projectIndex=0,projectPartIndex=0,jobIndex=0,eventIndex=0,logPageFromEnd=0,storePage=0,storeAisle='oil',storeView='aisles',modalContext='',pendingFailure=null,pendingSideFailure=null,pendingProjectApproach=null,marketIndex=0,partsMarketIndex=0,yardIndex=0,swapIndex=0,sellIndex=0,usedInvIndex=0,installedIndex=0;
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function item(id){return storeItems.find(x=>x.id===id)}
function ownedToolItems(){return storeItems.filter(i=>i.kind==='tool'&&(S.inventory[i.id]||0)>0)}
function bestScanner(){return ownedToolItems().filter(i=>i.obdTier).sort((a,b)=>(b.obdTier||0)-(a.obdTier||0))[0]||null}
function bestScannerTier(){const x=bestScanner();return x?x.obdTier:0}function sideJobScanner(){const x=bestScanner();return x&&x.id!=='obd_bt'?x:null}
function codeSignature(){return (S.activeCodes||[]).map(c=>c.code).sort().join('|')}
function dtcCandidates(code){return dtcRepairOptions[code]||[]}function ensureCelCause(c){if(!c)return null;if(!c.cause){const opts=dtcCandidates(c.code);c.cause=opts.length?opts[rand(0,opts.length-1)].itemId:null}return c.cause}function newCelInstance(base){const c={...base};ensureCelCause(c);return c}function randomCelCode(){return newCelInstance(celCodes[rand(0,celCodes.length-1)])}
function toolBonus(){return ownedToolItems().filter(i=>!i.obdTier).reduce((a,i)=>a+(i.toolBonus||0),0)}
function bodyToolBonus(){return ownedToolItems().reduce((a,i)=>a+(i.bodyBonus||0),0)}
function toolSummary(){const n=ownedToolItems().length;return n?`Starter kit + ${n}`:'Starter kit'}
function makeCars(){$('carChoices').innerHTML=cars.filter(c=>c.starter).map(c=>`<div class="car"><h3>${c.name}</h3><span class="tag">${c.trait}</span><p>${c.desc}</p><div class="price">$${c.price.toLocaleString()}</div><button onclick="startGame('${c.id}')">BUY THIS PROBLEM</button></div>`).join('')}

const bodyPanelDefs=[
 {id:'hood',name:'Hood'},{id:'front_bumper',name:'Front bumper'},{id:'lf_fender',name:'Left front fender'},{id:'rf_fender',name:'Right front fender'},
 {id:'left_door',name:'Left door'},{id:'right_door',name:'Right door'},{id:'trunk',name:'Trunk / hatch'},{id:'rear_bumper',name:'Rear bumper'}
];
function buildBodyPanels(base){const out={};for(const p of bodyPanelDefs)out[p.id]=clamp(base+rand(-14,14),18,92);return out}
function bodyAverage(panels=S.bodyPanels){const vals=Object.values(panels||{});return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):50}
function buildBodyPanelColors(base){const out={};for(const p of bodyPanelDefs)out[p.id]=base;return out}
function mismatchedPanelCount(){return Object.values(S.bodyPanelColors||{}).filter(c=>c&&c!==S.paintColor).length}
function panelIssue(v){if(v>=88)return 'very clean';if(v>=75)return 'minor scratches / fade';if(v>=60)return 'visible dents / paint damage';if(v>=42)return 'rough paint / rust starting';return 'heavy rust / damage'}
function appearanceScore(){return clamp(Math.round((S.bodyCondition||50)*.78+(S.cleanliness||50)*.12+(S.styleScore||0)*1.9-mismatchedPanelCount()*4),0,100)}
function bodyChance(req){return clamp(58+(effectiveKnowledge(S.car.make,'Bodywork')+bodyToolBonus()-req)*1.65-fatiguePenalty(),5,96)}
function bodyRisk(req){const c=bodyChance(req);return c>=85?'VERY SAFE':c>=70?'PROBABLY FINE':c>=50?'SKETCHY':c>=30?'BAD IDEA':'ABSOLUTELY NOT'}
function recalcBody(){S.bodyCondition=bodyAverage();}
function diminishingScale(v){if(v<25)return 1;if(v<40)return .65;if(v<60)return .40;if(v<78)return .22;return .10}
function addDiminishing(current,raw){return clamp(current+raw*diminishingScale(current),0,100)}
function learningRetention(raw=1){if(!S)return 1;const load=S.learningLoad||0;let r=load<6?1:load<12?.62:load<18?.32:.14;if(S.awakeHours>16)r*=.72;if(S.energy<35)r*=.82;S.learningLoad=load+Math.max(.25,raw);return clamp(r,.08,1)}
function calculateOverallKnowledge(){if(!S)return 0;const core=S.knowledgeCore??S.knowledge??0,skills=categories.map(c=>S.skillKnowledge[c]||0).sort((a,b)=>b-a).slice(0,4),skillAvg=skills.length?skills.reduce((a,b)=>a+b,0)/skills.length:0,vals=makes.map(m=>S.makeKnowledge[m]||0).sort((a,b)=>b-a).slice(0,3);while(vals.length<3)vals.push(0);const makeAvg=vals.reduce((a,b)=>a+b,0)/3;return clamp(Math.round(core*.60+skillAvg*.30+makeAvg*.10),0,100)}
function recalcOverallKnowledge(){if(S)S.knowledge=calculateOverallKnowledge()}
function gainGeneralKnowledge(raw){const kept=Math.max(.05,raw*learningRetention(raw*.7));S.knowledgeCore=addDiminishing(S.knowledgeCore??S.knowledge??0,kept);recalcOverallKnowledge()}
function startGame(id){
 const car=cars.find(x=>x.id===id),starterInv={oil_5w30:1,oil_10w30:1},mk={},sk={},cm={},cs={};makes.forEach(m=>{mk[m]=0;cm[m]=0});categories.forEach(c=>{sk[c]=1;cs[c]=2});mk[car.make]=12+car.bonusK;sk.Maintenance=6;sk.Engine=3;sk.Bodywork=2;cm[car.make]=14;cs.Maintenance=12;cs.Engine=8;cs.Bodywork=4;
 const bodyBase=clamp(car.progress+rand(14,28),32,68),bodyPanels=buildBodyPanels(bodyBase),paintColor=carColors[rand(0,carColors.length-1)],bodyPanelColors=buildBodyPanelColors(paintColor);
 S={car,totalMin:480,cash:3000-car.price,knowledge:0,knowledgeCore:10+car.bonusK*.4,confidence:18,reputation:0,progress:car.progress,reliability:car.reliability,tools:0,projectsOwned:1,jobs:[],events:[],energy:100,awakeHours:0,logs:[],completed:false,mileage:car.mileage,startable:true,driveable:true,inventory:starterInv,doneTasks:{},nextOilDue:car.mileage,nextPlugDue:car.mileage,knownProjectSpecs:false,lastJobRollDay:1,lastWakeMin:480,makeKnowledge:mk,skillKnowledge:sk,makeConfidence:cm,skillConfidence:cs,reputationChannels:{friends:4,workmanship:0,scene:0},contacts:{},projectClues:1,lastDiagnosedClue:0,learningLead:null,leadSeq:0,consumedLeadIds:[],studiedLeadKeys:[],focusedResearchToday:0,focusedResearchDay:1,learningLoad:0,casualResearchUsed:0,dailyResearchLimit:1,weeklyResearchUsed:0,weeklyResearchLimit:5,researchWeek:1,targetedResearchToday:0,researchTopicCounts:{},lastBasicInspectDay:0,activeCodes:[],lastScanSignature:'',location:'parents',parentPatience:68,deferred:[],choiceQueue:[],weeklyDue:null,weekStart:null,weekMetrics:{jobsSuccess:0,jobsFail:0,projectSuccess:0,projectFail:0,research:0,shiftHours:0,shiftPay:0,codesScanned:0,carsBought:0,junkPulls:0,partsBought:0,partsSold:0,swapDeals:0,bodyJobs:0},gameOver:false,usedParts:[],installedUpgrades:[],styleScore:0,performanceScore:0,bodyPanels,bodyCondition:bodyAverage(bodyPanels),cleanliness:rand(40,72),lastDetailDay:0,lastBodyStudyDay:0,paintColor,bodyPanelColors,projects:[],activeProjectUid:null,nextProjectId:2,marketDay:0,marketListings:[],partsMarketDay:0,partsMarketListings:[],yardsDay:0,yardsData:{},yardVisits:{},yardTrip:null,yardAlertCarIds:[],yardAlertSeen:[],lastYardAlertDay:0,swapWeek:0,swapListings:[],swapVisitedWeek:0,shiftJobDay:0,shiftJobIds:[],ftueEnabled:true,ftueShownDay:0,ftueStep:0,ftueNudge:null,seenTips:{}};
 recalcOverallKnowledge();S.projects=[captureActiveProject('p1',car.price)];S.activeProjectUid='p1';S.projectsOwned=1;sideJobTemplates.forEach(j=>S.contacts[j.owner]=50);S.weekStart={week:1,cash:S.cash,mileage:S.mileage,progress:S.progress,knowledge:S.knowledge,reputation:S.reputation};scheduleEvents();$('start').classList.add('hidden');$('game').classList.remove('hidden');
 addLog(`DAY 1 - You hand over $${car.price.toLocaleString()} for a ${car.name}.`,'day');addLog('It makes it home under its own power. This feels like a major victory.','good');addLog(`You know a little more about ${car.make}s than everything else. That is not saying much.`,'warn');addLog(`The ${S.paintColor.toLowerCase()} exterior is about ${S.bodyCondition}% overall. Some panels are absolutely going to need attention.`,'warn');addLog(`Your parents give you about ${locations.parents.capacity} inventory slots in the garage before they start asking questions.`,'day');if(Math.random()<.22){const c=randomCelCode();S.activeCodes=[c];S.projectClues++;addLog('The check-engine light is already on. Welcome to used-car ownership.','warn')}refreshDailyResearch(1,true);rollJobs();refreshShiftJobs(true);render();
}
function dayNum(){return Math.floor(S.totalMin/1440)+1}function minuteOfDay(){return ((S.totalMin%1440)+1440)%1440}
function weekNum(){return Math.floor((dayNum()-1)/7)+1}function clockStr(minute=minuteOfDay()){let h=Math.floor(minute/60),m=Math.floor(minute%60),ap=h>=12?'PM':'AM',h12=h%12||12;return `${h12}:${String(m).padStart(2,'0')} ${ap}`}
function itemSlots(id){return itemSlotOverrides[id]||1}function normalizeInstalledStorage(){if(!S)return;const ids=new Set((S.installedUpgrades||[]).map(p=>p&&p.uid).filter(Boolean));if(ids.size)S.usedParts=(S.usedParts||[]).filter(p=>!ids.has(p.uid))}function inventoryBreakdown(){normalizeInstalledStorage();let supplies=0,tools=0;for(const [id,n] of Object.entries(S.inventory||{})){if(!n)continue;const it=item(id),slots=n*itemSlots(id);if(it&&it.kind==='tool')tools+=slots;else supplies+=slots}const loose=(S.usedParts||[]).reduce((a,p)=>a+(p.slots||1),0);return {supplies,tools,loose,total:supplies+tools+loose}}function inventoryUsed(){return inventoryBreakdown().total}function inventoryCapacity(){return locations[S.location].capacity}function totalInventory(){return Object.values(S.inventory).reduce((a,b)=>a+b,0)+(S.usedParts||[]).length}function projectCapacity(){return locations[S.location].bays+(S.location==='parents'?1:0)}
function projectStateFields(){return ['progress','reliability','mileage','startable','driveable','doneTasks','nextOilDue','nextPlugDue','knownProjectSpecs','projectClues','lastDiagnosedClue','learningLead','activeCodes','lastScanSignature','completed','lastBasicInspectDay','installedUpgrades','styleScore','performanceScore','bodyPanels','bodyCondition','cleanliness','lastDetailDay','lastBodyStudyDay','paintColor','bodyPanelColors']}
function captureActiveProject(uid=S.activeProjectUid||'p1',purchasePrice=0){const p={uid,carId:S.car.id,purchasePrice};for(const k of projectStateFields()){const v=S[k];p[k]=(v&&typeof v==='object')?JSON.parse(JSON.stringify(v)):v}p.installedUpgrades=p.installedUpgrades||[];p.styleScore=p.styleScore||0;p.performanceScore=p.performanceScore||0;return p}
function syncActiveProject(){if(!S||!S.projects||!S.activeProjectUid)return;const p=S.projects.find(x=>x.uid===S.activeProjectUid);if(!p)return;const snap=captureActiveProject(p.uid,p.purchasePrice);Object.assign(p,snap);S.projectsOwned=S.projects.length}
function applyProject(p){const car=cars.find(c=>c.id===p.carId);if(!car)return;S.car=car;for(const k of projectStateFields()){let v=p[k];if(v===undefined){if(k==='installedUpgrades')v=[];else if(k==='styleScore'||k==='performanceScore')v=0;else if(k==='bodyPanels')v=buildBodyPanels(50);else if(k==='bodyCondition')v=50;else if(k==='cleanliness')v=55;else if(k==='lastDetailDay'||k==='lastBodyStudyDay')v=0;else if(k==='paintColor')v=carColors[rand(0,carColors.length-1)];else if(k==='bodyPanelColors')v=buildBodyPanelColors(p.paintColor||S.paintColor||'Silver');else if(k==='activeCodes')v=[];else if(k==='doneTasks')v={};else if(k==='learningLead')v=null;else if(k==='completed'||k==='knownProjectSpecs')v=false;else if(k==='startable'||k==='driveable')v=true;else if(k==='lastBasicInspectDay'||k==='lastDiagnosedClue')v=0;else if(k==='lastScanSignature')v='';else if(k==='projectClues')v=1}S[k]=(v&&typeof v==='object')?JSON.parse(JSON.stringify(v)):v}if(!S.bodyPanelColors)S.bodyPanelColors=buildBodyPanelColors(S.paintColor||'Silver');S.activeProjectUid=p.uid}
function switchProject(uid){if(uid===S.activeProjectUid){openProjects();return}syncActiveProject();const p=S.projects.find(x=>x.uid===uid);if(!p)return;passTime(.25,true);applyProject(p);closeModal();addLog(`You switch your attention to the ${S.car.name}.`,'day');render()}
function createProjectFromListing(l){const c=cars.find(x=>x.id===l.carId),uid=`p${S.nextProjectId++}`,paintColor=l.paintColor||carColors[rand(0,carColors.length-1)],bodyPanelColors=l.bodyPanelColors||buildBodyPanelColors(paintColor);return {uid,carId:c.id,purchasePrice:l.price,progress:l.progress,reliability:l.reliability,mileage:l.mileage,startable:true,driveable:true,doneTasks:{},nextOilDue:l.mileage,nextPlugDue:l.mileage,knownProjectSpecs:false,projectClues:1,lastDiagnosedClue:0,learningLead:null,activeCodes:l.hiddenIssue&&Math.random()<.55?[randomCelCode()]:[],lastScanSignature:'',completed:false,lastBasicInspectDay:0,installedUpgrades:[],styleScore:0,performanceScore:0,bodyPanels:l.bodyPanels||buildBodyPanels(l.bodyCondition||50),bodyCondition:l.bodyCondition||50,cleanliness:rand(32,68),lastDetailDay:0,lastBodyStudyDay:0,paintColor,bodyPanelColors}}
function projectState(){const cel=S.activeCodes&&S.activeCodes.length?' + CEL':'';if(!S.startable)return 'NO START'+cel;if(!S.driveable)return 'IMMOBILE'+cel;return 'STARTS / DRIVES'+cel}
function fatigueRisk(){if(S.awakeHours>=24||S.energy<20)return 'EXTREME';if(S.awakeHours>=20||S.energy<35)return 'VERY HIGH';if(S.awakeHours>=16||S.energy<50)return 'HIGH';if(S.awakeHours>=12||S.energy<70)return 'RISING';return 'LOW'}
function fatiguePenalty(){let p=0;if(S.awakeHours>12)p+=(S.awakeHours-12)*2.3;if(S.energy<70)p+=(70-S.energy)*.22;return p}
function syncReputation(){const r=S.reputationChannels;S.reputation=clamp(Math.round((r.friends+r.workmanship+r.scene)/3),0,100)}
function gainRep(channel,n){S.reputationChannels[channel]=clamp((S.reputationChannels[channel]||0)+n,0,100);syncReputation()}
function effectiveConfidence(make,category){return S.confidence*.45+(S.makeConfidence[make]||0)*.25+(S.skillConfidence[category]||0)*.30}
function gainConfidence(make,category,n){S.confidence=clamp(S.confidence+Math.max(1,Math.round(n*.45)),0,100);S.makeConfidence[make]=clamp((S.makeConfidence[make]||0)+Math.max(1,Math.round(n*.7)),0,100);S.skillConfidence[category]=clamp((S.skillConfidence[category]||0)+Math.max(1,Math.round(n*.8)),0,100)}
function loseConfidence(make,category,n){S.confidence=clamp(S.confidence-Math.max(1,Math.round(n*.45)),0,100);S.makeConfidence[make]=clamp((S.makeConfidence[make]||0)-Math.max(1,Math.round(n*.6)),0,100);S.skillConfidence[category]=clamp((S.skillConfidence[category]||0)-Math.max(1,Math.round(n*.7)),0,100)}
function garageNoiseCheck(hours=1){if(S.location!=='parents')return;const m=minuteOfDay();if((m>=1380||m<360)&&Math.random()<Math.min(.65,.18+hours*.05)){const hit=rand(3,8);S.parentPatience=clamp(S.parentPatience-hit,0,100);addLog(`Late-night wrenching wakes the house. Parent patience -${hit}.`,'warn')}}
function processDeferredForDay(d){const due=S.deferred.filter(x=>x.dueDay<=d),keep=S.deferred.filter(x=>x.dueDay>d);S.deferred=keep;for(const e of due){if(e.type==='sideComeback'){if(Math.random()<.72)S.choiceQueue.push(e);else addLog(`${e.owner} never calls back about the sketchy ${e.job.toLowerCase()}. Somehow, you got away with it.`,'warn')}}}
function processWeekBoundary(newWeek){const prev=S.weekStart,loc=locations[S.location],summary={week:prev.week,cashDelta:S.cash-prev.cash,miles:Math.round(S.mileage-prev.mileage),progress:S.progress-prev.progress,knowledge:S.knowledge-prev.knowledge,reputation:S.reputation-prev.reputation,metrics:{...S.weekMetrics},rent:loc.rent,location:loc.name,parentNote:''};if(S.location==='parents'&&inventoryUsed()>inventoryCapacity()){const over=inventoryUsed()-inventoryCapacity(),hit=clamp(8+over*3,8,30);S.parentPatience=clamp(S.parentPatience-hit,0,100);summary.parentNote=`You are ${over} slot${over===1?'':'s'} over the garage limit. Parent patience drops ${hit}. ${S.parentPatience<30?'They are now actively pushing you to clean the garage out or find somewhere else to work.':''}`;}
 if(loc.rent>0){S.cash-=loc.rent;addLog(`Weekly ${loc.name} rent: -$${loc.rent}.`,'warn')}
 S.weeklyDue=summary;S.weeklyResearchUsed=0;S.researchWeek=newWeek;S.weekMetrics={jobsSuccess:0,jobsFail:0,projectSuccess:0,projectFail:0,research:0,shiftHours:0,shiftPay:0,codesScanned:0,carsBought:0,junkPulls:0,partsBought:0,partsSold:0,swapDeals:0,bodyJobs:0};S.weekStart={week:newWeek,cash:S.cash,mileage:S.mileage,progress:S.progress,knowledge:S.knowledge,reputation:S.reputation};}
function refreshDailyResearch(d,silent=false){S.casualResearchUsed=0;S.targetedResearchToday=0;S.researchTopicCounts={};S.focusedResearchToday=0;S.focusedResearchDay=d;S.dailyResearchLimit=(d>=7&&Math.random()<.20)?2:1;const weeklyLeft=Math.max(0,S.weeklyResearchLimit-S.weeklyResearchUsed),today=Math.min(S.dailyResearchLimit,weeklyLeft);if(!silent&&today>0)addLog(`New day: ${today} random research rabbit hole${today===1?'':'s'} is available. Most learning should come from actually doing things, not reading forever.`,'day');if(!silent&&today===0)addLog('You have burned through enough casual research this week that more random reading is not teaching you much. Real problems can still create focused leads.','warn')}
function passTime(hours,awake=true){const oldDay=dayNum(),oldWeek=weekNum();S.totalMin+=Math.round(hours*60);if(awake){S.awakeHours+=hours;S.energy=clamp(S.energy-hours*4,0,100)}const newDay=dayNum(),newWeek=weekNum();if(newWeek>oldWeek)processWeekBoundary(newWeek);if(newDay>oldDay){for(let d=oldDay+1;d<=newDay;d++){addLog(`MIDNIGHT - Day ${d} begins. You are still ${S.awakeHours>=16?'awake for some reason':'alive'}.`,'day');if(d===3&&S.ftueEnabled)addLog('The first-days guide is over. From here on, nobody is telling you what a sensible day looks like.','good');processDeferredForDay(d);refreshDailyResearch(d);if(d>S.lastJobRollDay){rollJobs();S.lastJobRollDay=d}refreshShiftJobs(true)}}}
function addLog(msg,type=''){if(!S)return;S.logs.push({msg,type});logPageFromEnd=0;renderLog()}
function renderLog(){if(!S)return;const pageSize=12,total=S.logs.length,pages=Math.max(1,Math.ceil(total/pageSize));logPageFromEnd=clamp(logPageFromEnd,0,pages-1);const end=Math.max(0,total-logPageFromEnd*pageSize),start=Math.max(0,end-pageSize),slice=S.logs.slice(start,end);$('log').innerHTML=slice.map(x=>`<p class="${x.type==='good'?'goodtxt':x.type==='bad'?'badtxt':x.type==='warn'?'warntxt':x.type==='day'?'day':''}">&gt; ${x.msg}</p>`).join('');$('olderLogBtn').disabled=start===0;$('newerLogBtn').disabled=end===total;$('logPage').textContent=end===total?`Latest - ${total} entries`:`History ${pages-logPageFromEnd}/${pages} - ${total} entries`}
function ftueStepData(){
 const steps=[
  {label:'1 / 5 - DIAGNOSE THE CAR',detail:'Start by looking at the car. Diagnosis creates clues; it does not magically replace parts.',button:'diagnoseBtn',feature:'diagnose'},
  {label:'2 / 5 - LEARN SOMETHING',detail:'Follow the research lead created by your inspection. Useful information should come from something you actually observed.',button:'learnBtn',feature:'research'},
  {label:'3 / 5 - DO AN OIL CHANGE',detail:'Use what you learned. The guide keeps you on the oil service and walks you through any supplies you are missing.',button:'workBtn',feature:'work'},
  {label:'4 / 5 - EARN SOME MONEY',detail:'Take one job from the Part-Time Shift board. Project cars eat money, so wrenching cannot be your entire day.',button:'shiftBtn',feature:'shift'},
  {label:'5 / 5 - SLEEP',detail:'Your first day ends with sleep. During the tutorial, bedtime is locked until 10:00 PM so time and fatigue make sense.',button:'sleepBtn',feature:'sleep'},
 ];
 return steps[clamp(S.ftueStep||0,0,steps.length-1)];
}
function ftueActive(){return !!(S&&S.ftueEnabled&&dayNum()===1&&(S.ftueStep||0)<5)}
function ftueBedtimeReady(){return minuteOfDay()>=1320}
function ftueFeatureAllowed(key){if(!ftueActive())return true;const g=ftueStepData();return key===g.feature&&(!(S.ftueStep===4)||ftueBedtimeReady())}
function applyFtueGuards(){
 const actionIds=['workBtn','diagnoseBtn','jobsBtn','storeBtn','learnBtn','driveBtn','shiftBtn','homeBtn','worldBtn','sleepBtn'];
 const alwaysOn=['workBtn','jobsBtn','storeBtn','driveBtn','shiftBtn','homeBtn','worldBtn','sleepBtn'];
 const statIds=['inventoryStat','toolsStat','knowledgeStat','confidenceStat','repStat'];
 if(!ftueActive()){
  alwaysOn.forEach(id=>{const el=$(id);if(el)el.disabled=false});
  statIds.forEach(id=>{const el=$(id);if(el)el.classList.remove('ftue-stat-locked')});
  return;
 }
 actionIds.forEach(id=>{const el=$(id);if(el)el.disabled=true});
 statIds.forEach(id=>{const el=$(id);if(el)el.classList.add('ftue-stat-locked')});
 const g=ftueStepData(),el=$(g.button);if(el&&(!(S.ftueStep===4)||ftueBedtimeReady()))el.disabled=false;
}
function updateFtueTarget(){
 ['diagnoseBtn','learnBtn','workBtn','shiftBtn','sleepBtn','ftueWindBtn'].forEach(id=>{const el=$(id);if(el)el.classList.remove('ftue-target')});
 if(!ftueActive())return;
 const d=ftueStepData();
 if(S.ftueStep===4&&!ftueBedtimeReady()){const w=$('ftueWindBtn');if(w)w.classList.add('ftue-target');return}
 const el=$(d.button);if(el)el.classList.add('ftue-target');
}
function renderGuidePanel(){
 const p=$('guidePanel');if(!p)return;
 if(ftueActive()){
  const g=ftueStepData();
  if(S.ftueStep===4&&!ftueBedtimeReady()){
   p.innerHTML=`<b>FIRST DAY // BEDTIME IS 10:00 PM</b><div class="small" style="margin-top:5px">You finished the required work, but it is only <b>${clockStr()}</b>. Use the rest of the evening for dinner, a shower, TV, texting friends, or staring at the car. Sleep unlocks at 10:00 PM.</div><button class="ftue-wind" id="ftueWindBtn" onclick="ftueWindDown()">WIND DOWN UNTIL 10:00 PM</button><div id="fatigueNote" class="small warning" style="margin-top:5px"></div>`;
  }else p.innerHTML=`<b>FIRST DAY // ${g.label}</b><div class="small" style="margin-top:5px">${g.detail}</div><div class="small" style="margin-top:5px">Everything else is temporarily locked. You can skip the Day 1 guide from the tutorial screens.</div><div id="fatigueNote" class="small warning" style="margin-top:5px"></div>`;
  return;
 }
 p.innerHTML=`<b>Everything has a downside now.</b> <span class="small">Diagnosis creates clues. Research can help or mislead you. Repairs cost time and supplies. Driving creates mileage and risk. Reputation, confidence, storage, money and sleep all matter.</span><div id="fatigueNote" class="small warning" style="margin-top:5px"></div>`;
}
function ftueWindDown(){
 if(!ftueActive()||S.ftueStep!==4||ftueBedtimeReady())return;
 const mins=1320-minuteOfDay(),hours=mins/60;S.totalMin+=mins;S.awakeHours+=hours;S.energy=clamp(S.energy-hours*1.5,0,100);
 addLog('You kill the rest of the evening at home. Dinner, shower, a little TV, and several unnecessary looks at the project later, it is 10:00 PM.','day');render();
}
function ftueAdvance(completedStep,msg){
 if(!S.ftueEnabled||(S.ftueStep||0)!==completedStep)return;
 S.ftueStep=completedStep+1;S.ftueNudge=msg||'';
}
function showFtueNudge(){
 if(!S.ftueNudge)return;const msg=S.ftueNudge;S.ftueNudge=null;
 const done=(S.ftueStep||0)>=5,g=done?null:ftueStepData();
 showModal(`<h2>${done?'Day 1 complete':'Good. Next step.'}</h2><div class="card"><p>${msg}</p>${done?`<p><b>You now know the basic loop:</b> diagnose -> learn -> wrench -> earn -> sleep.</p><p class="small">The guard rails are gone. First-use explanations still appear when you open unfamiliar systems, but Day 2 onward is yours.</p>`:`<p><b>${g.label}</b></p><p class="small">${g.detail}</p>`}</div><div class="modal-actions"><button class="primary" onclick="closeFtueNudge()">${done?'START DAY 2':'GOT IT'}</button>${done?'':`<button onclick="disableFtue()">SKIP DAY 1 GUIDE</button>`}</div>`)
}
function closeFtueNudge(){closeModal();render()}
function showFtueDay(){
 const d=dayNum();if(!S.ftueEnabled||d!==1||S.ftueShownDay===1)return;S.ftueShownDay=1;
 showModal(`<h2>Day 1 - learn the basic loop</h2><div class="card"><p>You are 18, you just bought an old car, and the game is going to keep your first day intentionally simple.</p><p><b>Today only:</b> Diagnose -> Research -> Oil Change -> Part-Time Job -> Sleep.</p><p>Buttons you do not need are disabled. Each step explains what the system is teaching you. After you sleep, the guard rails disappear completely.</p><p class="small">This is not the correct routine forever. It is just enough structure to stop a first-time player from drowning in menus.</p></div><div class="modal-actions"><button class="primary" onclick="closeModal();render()">START DAY 1</button><button onclick="disableFtue()">SKIP DAY 1 GUIDE</button></div>`);
}
function disableFtue(){S.ftueEnabled=false;S.ftueNudge=null;closeModal();render()}
const featureTips={
 diagnose:{title:'Diagnosis is information, not a repair',body:'Inspections and symptom checks cost time. They can expose clues and create focused research leads, but they do not magically tell you which part to replace.'},
 research:{title:'Research can be useful. It can also be garbage.',body:'Focused leads come from things you actually observed and are much more useful. Random rabbit holes can teach you something unrelated, waste time, or confidently teach you the wrong thing.'},
 work:{title:'This is where parts actually become a car',body:'Mechanical service, body work, interior parts and upgrades all happen here. Jobs consume time and supplies. Routine service only appears when it is actually due, and harder jobs will ask whether you want the safer route or to risk it.'},
 jobs:{title:'Friends and family remember what you do to their cars',body:'Side jobs are extra money and experience, but the car belongs to somebody you know. A bad failure can hurt trust, reputation, or leave you paying a real shop to fix your mistake.'},
 store:{title:'Parts stores sell possibilities, not answers',body:'Supplies, tools, tires and upgrades live in aisles. Your garage has limited storage. Supplies bought specifically for a side job are used for that job instead of becoming permanent inventory.'},
 drive:{title:'Driving is part of owning the project',body:'Trips add real mileage, advance service intervals, consume time, get the car dirty and can expose new problems. Longer drives carry more risk.'},
 shift:{title:'The work board changes every day',body:'Only six part-time jobs appear at once. Early jobs are normal teenager work; automotive and higher-paying work enters the pool as your real knowledge and reputation improve.'},
 home:{title:'Your parents do not own a warehouse',body:'Housing controls project-car space and inventory capacity. Hoard too much stuff or fill the driveway and your parents can start pushing you toward a more expensive place of your own.'},
 world:{title:'Old-car ownership happens outside the parts store',body:'Marketplace, Pull-A-Part yards and swap meets are how you find projects and weird used parts. Availability, distance, transport space, condition and seller honesty all matter.'},
 sleep:{title:'Sleep is a resource too',body:'You can sleep up to eight hours. Too little sleep, terrible bedtimes and random bad nights reduce recovery. Staying awake too long makes mechanical work substantially riskier.'},
 inventory:{title:'Inventory means physical garage space',body:'Oil, filters, parts and used junk take actual slots. Stored used parts are not installed from here; put them on the car through Work on Project.'},
 tools:{title:'Tools are individual equipment now',body:'Open this whenever you want to see what you actually own. Better hand tools, specialty tools and scanners improve what you can safely attempt; owning one generic "tool level" does not.'},
 knowledge:{title:'Overall Knowledge is only the headline number',body:'Your real ability is split across makes and systems such as Maintenance, Engine, Brakes and Electrical. Experience also slows down as you become more knowledgeable.'},
 confidence:{title:'Confidence is not the same as competence',body:'Confidence is also split by make and type of work. Too little can make you hesitant; too much confidence compared with your actual knowledge can push you into bad decisions.'},
 reputation:{title:'Different people know you for different things',body:'Friends/family trust, workmanship and the local car scene are separate. A clean show car, a successful brake job and admitting a mistake can affect different kinds of reputation.'}
};
function executeFeature(key){switch(key){case'diagnose':diagnose();break;case'research':openResearch();break;case'work':projectWork();break;case'jobs':openJobs();break;case'store':openStore();break;case'drive':openDrive();break;case'shift':openShiftJobs();break;case'home':openHome();break;case'world':openWorld();break;case'sleep':openSleep();break;case'inventory':openInventory();break;case'tools':openTools();break;case'knowledge':openKnowledge();break;case'confidence':openConfidence();break;case'reputation':openReputation();break}}
function openFeature(key){
 if(!ftueFeatureAllowed(key))return;
 S.seenTips=S.seenTips||{};const tip=featureTips[key];
 if(!tip||S.seenTips[key]){executeFeature(key);return}
 S.seenTips[key]=true;showModal(`<h2>${tip.title}</h2><div class="card"><p>${tip.body}</p></div><div class="modal-actions"><button class="primary" onclick="continueFeature('${key}')">CONTINUE</button>${ftueActive()?'<button onclick="disableFtue()">SKIP DAY 1 GUIDE</button>':''}</div>`)
}
function continueFeature(key){closeModal();executeFeature(key)}
function nextEventText(){refreshEvents();const e=activeEvents()[0];return e?`D${e.day} ${clockStr(e.startHour*60)}`:'NONE'}
function render(){
 if(!S)return;normalizeInstalledStorage();refreshEvents();if(dayNum()>1&&S.ftueEnabled&&(S.ftueStep||0)<5){S.ftueEnabled=false;S.ftueNudge=null;addLog('Day 1 is over. The tutorial guard rails shut off; from here, you are on your own.','day')}syncActiveProject();S.projectsOwned=S.projects?S.projects.length:1;recalcOverallKnowledge();renderGuidePanel();S.cash=Math.round(S.cash);['confidence','progress','reliability','energy'].forEach(k=>S[k]=clamp(Math.round(S[k]),0,100));Object.keys(S.reputationChannels).forEach(k=>S.reputationChannels[k]=clamp(Math.round(S.reputationChannels[k]),0,100));syncReputation();if(S.knowledge>=20)S.knownProjectSpecs=true;
 $('carName').textContent=S.car.name;$('day').textContent=dayNum();$('time').textContent=clockStr();$('cash').textContent=(S.cash<0?'-$':'$')+Math.abs(S.cash).toLocaleString();$('energy').textContent=S.energy+'%';$('knowledge').textContent=S.knowledge;$('confidence').textContent=S.confidence;$('rep').textContent=S.reputation;$('tools').textContent=toolSummary();$('inventoryCount').textContent=`${inventoryUsed()} / ${inventoryCapacity()} slots`;
 $('progress').textContent=S.progress+'%';$('reliability').textContent=S.reliability+'%';$('mileage').textContent=Math.round(S.mileage).toLocaleString()+' mi';$('carState').textContent=projectState();$('jobsCount').textContent=`${S.jobs.length} waiting`;$('fatigueRisk').textContent=fatigueRisk();$('oilDue').textContent=S.mileage>=S.nextOilDue?'DUE':`${Math.round(S.nextOilDue-S.mileage)} mi`;$('nextEvent').textContent=nextEventText();
 ['energy','knowledge','confidence','progress','reliability'].forEach(k=>$(k+'Bar').style.width=S[k]+'%');$('repBar').style.width=S.reputation+'%';$('clockTag').textContent=`Day ${dayNum()} - ${weekdayName()} - ${clockStr()}`;$('awakeTag').textContent=`Awake ${S.awakeHours.toFixed(1)}h`;$('fatigueNote').textContent=S.awakeHours>=16?`You have been awake ${S.awakeHours.toFixed(1)} hours. Mechanical judgment is getting ugly.`:(S.location==='parents'&&S.parentPatience<30?`Your parents are getting tired of the garage situation. Patience: ${S.parentPatience}%.`:'');
 const researchRemaining=researchLeftToday(),canScan=S.activeCodes.length&&bestScannerTier()>0&&S.lastScanSignature!==codeSignature(),canInspect=S.lastBasicInspectDay!==dayNum(),canDiagnose=S.lastDiagnosedClue<S.projectClues;$('diagnoseBtn').disabled=!canInspect&&!canDiagnose&&!canScan;$('learnBtn').disabled=!S.learningLead&&researchRemaining<=0;$('learnBtn').textContent=S.learningLead?'RESEARCH CURRENT LEAD':researchRemaining>0?`RESEARCH / LEARN (${researchRemaining} RANDOM)`:'RESEARCH / LEARN';
 if(S.progress>=100&&S.bodyCondition>=72&&!S.completed){S.completed=true;addLog('THE CAR IS "DONE." Mechanically sorted enough and the exterior no longer looks abandoned. This is obviously still a lie.','good');addLog('Milestone reached: FIRST PROJECT COMPLETED. The game continues.','day')}
 if(S.cash<=-750&&!S.gameOver){S.gameOver=true;showGameOver();return}syncActiveProject();renderLog();
 applyFtueGuards();updateFtueTarget();
 if($('modal').classList.contains('hidden')){if(S.choiceQueue.length)showDeferredChoice();else if(S.weeklyDue)showWeeklySummary();else if(S.ftueNudge)showFtueNudge();else if(S.ftueEnabled&&dayNum()===1&&S.ftueShownDay!==1)showFtueDay()}
}
function effectiveKnowledge(make,category){return S.knowledge*.45+(S.makeKnowledge[make]||0)*.25+(S.skillKnowledge[category]||0)*.30}
function riskLabel(req,make=S.car.make,category='Engine'){const e=effectiveKnowledge(make,category)+toolBonus()-fatiguePenalty(),g=e-req;if(g>=15)return 'VERY SAFE';if(g>=5)return 'PROBABLY FINE';if(g>=-5)return 'SKETCHY';if(g>=-15)return 'BAD IDEA';return 'ABSOLUTELY NOT'}
function confidenceRead(req,make=S.car.make,category='Engine'){const e=effectiveKnowledge(make,category)+toolBonus(),c=effectiveConfidence(make,category);if(c>=req+20&&e<req-5)return 'Your confidence is outrunning your actual experience.';if(e>=req+10&&c<req-10)return 'You probably know enough, but you do not trust yourself yet.';if(e>=req)return `Your experience with ${make} / ${category.toLowerCase()} work says this is reasonable.`;return `You are weak on ${make} / ${category.toLowerCase()} experience for this job.`}
function chanceFor(req,base=60,make=S.car.make,category='Engine'){const e=effectiveKnowledge(make,category),c=effectiveConfidence(make,category);let conf=Math.min(c,55)*.08;if(c-e>25)conf-=(c-e-25)*.16;return clamp(base+(e+toolBonus()-req)*2+conf-fatiguePenalty(),5,97)}
function gainExperience(make,category,xp){const raw=Math.max(.15,xp),kept=raw*learningRetention(raw);S.knowledgeCore=addDiminishing(S.knowledgeCore??S.knowledge??0,kept*.30);S.makeKnowledge[make]=addDiminishing(S.makeKnowledge[make]||0,kept*.55);S.skillKnowledge[category]=addDiminishing(S.skillKnowledge[category]||0,kept*.75);recalcOverallKnowledge();return kept}
function showModal(html,context=''){modalContext=context;$('modalBox').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){modalContext='';$('modal').classList.add('hidden')}
function invHas(needs){return Object.entries(needs||{}).every(([id,n])=>(S.inventory[id]||0)>=n)}function consume(needs){for(const [id,n] of Object.entries(needs||{}))S.inventory[id]=(S.inventory[id]||0)-n}
function needNames(needs){const arr=Object.entries(needs||{}).map(([id,n])=>`${item(id)?.name||id} x${n}`);return arr.length?arr.join(', '):'No parts required'}function needCost(needs){return Object.entries(needs||{}).reduce((sum,[id,n])=>sum+(item(id)?.price||0)*n,0)}
function maybeNonsense(chance=.24){if(Math.random()>chance)return;const e=nonsense[rand(0,nonsense.length-1)];e.effect(S);passTime(e.hours,true);addLog(`${e.msg} (+${e.hours}h)`,e.t)}
function driveTrip(miles,hours,label,risk=true){if(!S.startable||!S.driveable)return false;S.mileage+=miles;S.cleanliness=clamp((S.cleanliness||55)-Math.max(1,Math.round(miles/18)),0,100);passTime(hours,true);if(risk&&Math.random()*100>Math.max(12,S.reliability)){S.reliability-=rand(1,4);S.projectClues++;addLog(`${label}: the project develops a new noise on the way. Fantastic.`,'warn')}return true}

function openKnowledge(){const knownMakes=makes.filter(m=>(S.makeKnowledge[m]||0)>0).sort((a,b)=>S.makeKnowledge[b]-S.makeKnowledge[a]);const topSkills=categories.map(c=>S.skillKnowledge[c]||0).sort((a,b)=>b-a).slice(0,4),skillAvg=topSkills.reduce((a,b)=>a+b,0)/Math.max(1,topSkills.length),topMakes=makes.map(m=>S.makeKnowledge[m]||0).sort((a,b)=>b-a).slice(0,3),makeAvg=topMakes.reduce((a,b)=>a+b,0)/3;showModal(`<h2>Knowledge breakdown</h2><div class="card"><b>Overall Knowledge: ${S.knowledge}</b><p class="small">Overall is not a simple XP counter: 60% broad foundation + 30% your strongest four systems + 10% your strongest three makes. One Civic can make you good at Civics without instantly making you a master mechanic.</p><div class="kv"><div><span>FOUNDATION</span><b>${Math.round(S.knowledgeCore||0)}</b></div><div><span>TOP SYSTEM AVG</span><b>${Math.round(skillAvg)}</b></div><div><span>TOP MAKE AVG</span><b>${Math.round(makeAvg)}</b></div></div><p class="small">Learning slows naturally as a topic rises, and cramming has diminishing returns. After several meaningful learning sessions while awake, less of it sticks until you sleep. Hands-on work is still the best long-term path.</p></div><div class="knowledgegrid">${categories.map(c=>`<div><span class="small">${c.toUpperCase()}</span><b>${Math.round(S.skillKnowledge[c]||0)}</b></div>`).join('')}</div><h2 style="margin-top:9px">Make familiarity</h2><div class="knowledgegrid">${knownMakes.map(m=>`<div><span class="small">${m.toUpperCase()}</span><b>${Math.round(S.makeKnowledge[m])}</b></div>`).join('')||'<div>None</div>'}</div><div class="modal-actions"><button onclick="closeModal()">CLOSE</button></div>`)}
function openConfidence(){const knownMakes=makes.filter(m=>(S.makeConfidence[m]||0)>0).sort((a,b)=>S.makeConfidence[b]-S.makeConfidence[a]);showModal(`<h2>Confidence breakdown</h2><div class="card"><b>General confidence: ${S.confidence}</b><p class="small">Confidence is experience you trust yourself to use. Too much confidence compared with Knowledge can actually hurt difficult jobs.</p></div><div class="knowledgegrid">${categories.map(c=>`<div><span class="small">${c.toUpperCase()}</span><b>${S.skillConfidence[c]||0}</b></div>`).join('')}</div><h2 style="margin-top:9px">Make confidence</h2><div class="knowledgegrid">${knownMakes.map(m=>`<div><span class="small">${m.toUpperCase()}</span><b>${S.makeConfidence[m]}</b></div>`).join('')||'<div>None</div>'}</div><div class="modal-actions"><button onclick="closeModal()">CLOSE</button></div>`)}
function openReputation(){const r=S.reputationChannels,contacts=Object.entries(S.contacts).sort((a,b)=>b[1]-a[1]).slice(0,6);showModal(`<h2>Reputation</h2><div class="card"><b>Overall reputation: ${S.reputation}</b><p class="small">Different people care about different things. Being known at meets is not the same as being trusted with someone's brakes.</p></div><div class="knowledgegrid"><div><span class="small">FRIENDS / FAMILY</span><b>${r.friends}</b></div><div><span class="small">WORKMANSHIP</span><b>${r.workmanship}</b></div><div><span class="small">CAR SCENE</span><b>${r.scene}</b></div></div><h2 style="margin-top:9px">People</h2><div class="knowledgegrid">${contacts.map(([n,v])=>`<div><span class="small">${n.toUpperCase()}</span><b>${v} - ${contactMood(n)}</b></div>`).join('')}</div><div class="modal-actions"><button onclick="closeModal()">CLOSE</button></div>`)}
function openTools(){const tools=ownedToolItems(),scan=bestScanner(),rows=tools.map(t=>`<div class="invrow"><div><b>${t.name}</b><div class="small">${t.desc}</div></div><div style="text-align:right">${t.toolBonus?`MECH +${t.toolBonus}<br>`:''}${t.bodyBonus?`BODY +${t.bodyBonus}<br>`:''}${t.obdTier?`OBD T${t.obdTier}`:''}</div></div>`).join('');showModal(`<h2>Your Tools</h2><div class="card"><b>Starter hand-tool kit</b><p class="small">Cheap ratchet, random sockets, screwdrivers, pliers, adjustable wrench, hammer and assorted inherited junk. Enough to begin; not enough to make hard jobs easy.</p><div class="kv"><div><span>PURCHASED TOOLS</span><b>${tools.length}</b></div><div><span>MECHANICAL BONUS</span><b>+${toolBonus()}</b></div><div><span>BODY BONUS</span><b>+${bodyToolBonus()}</b></div></div>${scan?`<p><b>Best scanner:</b> ${scan.name} (Tier ${scan.obdTier})</p>${S.activeCodes.length?'<p class="badtxt"><b>CHECK ENGINE LIGHT: ON</b></p>':''}`:'<p class="small">No OBD-II scanner yet.</p>'}</div><div class="inventorygrid">${rows||'<div class="invrow">No upgraded tools yet.</div>'}</div><div class="modal-actions">${scan?`<button class="primary" onclick="scanFromTools()" ${S.activeCodes.length?'':'disabled'}>USE SCANNER${S.activeCodes.length?' - CEL ON':''}</button>`:''}<button onclick="closeModal()">CLOSE</button></div>`)}
function scanFromTools(){if(!bestScanner())return;if(!S.activeCodes.length){showModal(`<h2>No CEL to scan</h2><div class="card"><p>The check-engine light is off and there are no known active codes right now.</p></div><div class="modal-actions"><button onclick="openTools()">BACK</button></div>`);return}scanProjectCodes('tools')}
