plugins {
    id 'com.android.application'
}

android {
    namespace 'com.techx1320.wrenchlife'
    compileSdk 36

    defaultConfig {
        applicationId 'com.techx1320.wrenchlife'
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName '0.1.0-alpha'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
